baseURL = 'https://blog.oftheangels.org/'
languageCode = 'en-us'
title = 'Musings of a Veteran CTO'
# Don't use a theme, rely on our layouts
theme = "hugo-theme-stack"
[services]
[services.googleAnalytics]
id = "G-FFPF3E5XZ5"


[params]
featuredImageField = true
rssFullContent = true

[[params.widgets.homepage]]
type = "search"

[[params.widgets.homepage]]
type = "archives"

[params.widgets.homepage.params]
limit = 5

[[params.widgets.homepage]]
type = "categories"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.homepage]]
type = "tag-cloud"

[params.widgets.homepage.params]
limit = 10

[[params.widgets.page]]
type = "toc"


[params.contact]
email = 'leo.dangelo@fortiumpartners.com'
[params.sidebar]
subtitle = 'A veteran CTO with 40+ years of experience in software development, cloud infrastructure, and technology leadership.'
[params.sidebar.avatar]
enabled = true
src = "headshot.jpg"
local = true

[caches]
[caches.images]
dir = ':cacheDir/images'

[menu]
[[menu.main]]
name = "About Me"
url = "/about"
weight = 10
[menu.main.params]
icon = "user"

[[menu.social]]
name = "Github"
url = "https://github.com/ldangelo"
[menu.social.params]
icon = "brand-github"
[[menu.social]]
name = "Linkedin"
url = "https://www.linkedin.com/in/leo-d-angelo-5a0a83/"
[menu.social.params]
icon = "linkedin"
[[menu.social]]
name = "Twitter"
url = "https://x.com/ldangelo"
[menu.social.params]
icon = "x"


[imageProcessing]
[cover]
enabled = true
[content]
enabled = true
